/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthenticatedLayout: typeof import('./src/components/layouts/AuthenticatedLayout.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    Button: typeof import('primevue/button')['default']
    CalendarDayBadge: typeof import('./src/components/Planner/CalendarDayBadge.vue')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    CoreInputText: typeof import('./src/components/core/CoreInputText.vue')['default']
    DayColumn: typeof import('./src/components/Planner/DayColumn.vue')['default']
    DeleteMealDialog: typeof import('./src/components/MealLibrary/DeleteMealDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    FamilyChip: typeof import('./src/components/FamilyChip.vue')['default']
    FamilySetupDialog: typeof import('./src/components/FamilySetupDialog.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    IngredientItem: typeof import('./src/components/ShoppingList/IngredientItem.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MealCard: typeof import('./src/components/MealLibrary/MealCard.vue')['default']
    MealCardBase: typeof import('./src/components/MealCardBase.vue')['default']
    MealCardCompact: typeof import('./src/components/MealCardCompact.vue')['default']
    MealForm: typeof import('./src/components/MealLibrary/MealForm.vue')['default']
    MealLibraryDialog: typeof import('./src/components/MealLibrary/MealLibraryDialog.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MobileHeader: typeof import('./src/components/MobileHeader.vue')['default']
    Password: typeof import('primevue/password')['default']
    PlannedMealCard: typeof import('./src/components/Planner/PlannedMealCard.vue')['default']
    Planner: typeof import('./src/components/Planner/Planner.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    ShoppingList: typeof import('./src/components/ShoppingList/ShoppingList.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    WeekNavigator: typeof import('./src/components/WeekNavigator.vue')['default']
    WeekView: typeof import('./src/components/Planner/WeekView.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
