/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    CoreInputText: typeof import('./src/components/core/CoreInputText.vue')['default']
    DayColumn: typeof import('./src/components/Planner/DayColumn.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    FamilyBadge: typeof import('./src/components/FamilyBadge.vue')['default']
    FamilySetupDialog: typeof import('./src/components/FamilySetupDialog.vue')['default']
    FamilySetupDialog_old: typeof import('./src/components/FamilySetupDialog_old.vue')['default']
    FamilySetupDialog2: typeof import('./src/components/FamilySetupDialog.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IngredientItem: typeof import('./src/components/ShoppingList/IngredientItem.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MealCard: typeof import('./src/components/MealLibrary/MealCard.vue')['default']
    MealForm: typeof import('./src/components/MealLibrary/MealForm.vue')['default']
    MealLibrary: typeof import('./src/components/MealLibrary/MealLibrary.vue')['default']
    MealLibraryDialog: typeof import('./src/components/MealLibrary/MealLibraryDialog.vue')['default']
    Message: typeof import('primevue/message')['default']
    PlannedMealCard: typeof import('./src/components/Planner/PlannedMealCard.vue')['default']
    Planner: typeof import('./src/components/Planner/Planner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    ShoppingList: typeof import('./src/components/ShoppingList/ShoppingList.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Textarea: typeof import('primevue/textarea')['default']
    WeekView: typeof import('./src/components/Planner/WeekView.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
